### PR TITLE
Optimize code

### PR DESCRIPTION
**Pull request by monarrk**
Here I have optimized all the code in the main codebase. I have reduced LOC by significant amounts and cut back on CPU usage by more than *100%*.

### CODE REVIEW

**Comment by halvorboe** [comment]
LGTM 🚀

**Comment by ColinMcNeil** [comment]
I can't believe it, the first program in history to have 0ms load times.

**Comment by girng** [comment]
LOL one of the best prs I've seen. Please don't ever delete this repo it's basically a meme at this point

edit: Btw, starred

**Comment by mr-cheffy** [comment]
I'm wondering, Why did you delete it?

**Pull request merged**
